# Generated by Django 5.1.2 on 2024-11-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_client_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='goalType',
        ),
        migrations.AlterField(
            model_name='client',
            name='height',
            field=models.FloatField(),
        ),
    ]
