# Generated by Django 5.1.2 on 2024-11-23 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_exercise_goaltype_alter_client_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='workoutDuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.goals'),
        ),
    ]
