# Generated by Django 5.1.2 on 2024-11-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_workoutplan_workoutduration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='workoutDuration',
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='workoutDuration',
            field=models.ManyToManyField(to='app.goals'),
        ),
    ]
