# Generated by Django 5.1.2 on 2024-11-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_workoutplan_workoutduration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplan',
            old_name='workoutDuration',
            new_name='workoutGoal',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='workoutPlanType',
        ),
    ]
