# Generated by Django 5.1.2 on 2024-11-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_workoutduration_workoutplan_workoutgoal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workoutType',
        ),
        migrations.AddField(
            model_name='exercise',
            name='workoutType',
            field=models.ManyToManyField(to='app.workoutplan'),
        ),
    ]
