# Generated by Django 5.1.2 on 2024-11-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_exercise_workouttype_exercise_workouttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='workoutProgram',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
