# Generated by Django 5.1.2 on 2024-12-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_workoutplan_workoutprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
