# Generated by Django 5.1.2 on 2024-12-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_client_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='weight',
            field=models.FloatField(),
        ),
    ]
