# Generated by Django 5.1.2 on 2024-12-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_client_activitylevel_client_clientsex'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
