# Generated by Django 5.1.2 on 2024-12-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_client_bmi_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='goalType',
            new_name='goal_name',
        ),
    ]
