# Generated by Django 5.1.2 on 2024-12-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_goaltype_goals_goal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='workoutProgram',
            field=models.TextField(max_length=500),
        ),
    ]
