# Generated by Django 5.1.2 on 2024-12-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_workoutplan_workoutprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='workoutProgram',
            field=models.TextField(max_length=1200),
        ),
    ]
