# Generated by Django 5.1.2 on 2025-01-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_workoutplan_workoutprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='workoutLink',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
