# Generated by Django 5.1.2 on 2025-01-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_goal_name_goals_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='name',
            new_name='goal',
        ),
    ]
