# Generated by Django 5.1.1 on 2025-01-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='workoutClientName',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='workoutPlanDateCreated',
        ),
    ]
