# Generated by Django 5.1.1 on 2025-01-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_workoutlog_workoutclientname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='workoutClientName',
            field=models.ManyToManyField(to='app.client'),
        ),
    ]
